# Generated by Django 4.0.5 on 2022-07-18 10:42

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airport',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='airport',
            name='airport_code',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
