# Generated by Django 4.0.5 on 2022-07-18 10:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0002_alter_airport_options_alter_airport_airport_code_and_more'),
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['aeroplane', 'departure_datetime']},
        ),
        migrations.AlterField(
            model_name='flight',
            name='aeroplane',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='airport_departure', to='airport.airport'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='airport_destination', to='airport.airport'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='max_passengers',
            field=models.PositiveIntegerField(),
        ),
    ]
